### PR TITLE
Fixes #325: Enforce maximum NetBox version for v0.6

### LINKED ISSUE #325: 'function' object has no attribute 'items' after upgrading to 4.4.0
### Plugin Version

0.6.1

### NetBox Version

4.4.0

### Python Version

3.12

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Observed Behavior

After upgrading nettbox to 4.4.0, netbox fails to run with the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/netbox", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/usr/lib/python3.12/site-packages/netbox_branching/__init__.py", line 53, in ready
    for app_label, models in registry['model_features']['change_logging'].items():
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'items'
```

https://github.com/netbox-community/netbox/commit/a59da37ac3a41ed40b361dac3a1b17312a887076 changes the value of `change_logging` from `ChangeLoggingMixin`  to a lambda

### PR DESCRIPTION
**Pull request by jeremystretch**
### Fixes: #325

Enforce a maximum NetBox version of 4.3.x for plugin version 0.6.x.

### CODE REVIEW

**Comment by jeremystretch** [comment]
CI is failing because the tests are running against NetBox v4.4.0.
